Resources:
  productsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_products
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: index_key
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: indexName
          KeySchema:
            - AttributeName: index_key
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    StreamSpecification:
      StreamViewType: NEW_IMAGE
  dataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}_data
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: index_key
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: indexName
          KeySchema:
            - AttributeName: index_key
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

